Repository LE-VAN-KET/apartment-online-market, pull requests merged in 2022-12, with the labels that each got.

#5 fix: jenkinsfile run test failure
  Jenkinsfile
Labels: bug

#10 fix: copy file deploy.sh to server failur permission denied
  Jenkinsfile
Labels: bug

#11 fix: copy file to wrongs paths remote server
  Jenkinsfile
Labels: bug

#12 fix: CORSFilter class cast servletResquest exception
  src/main/java/com/cdcn/apartmentonlinemarket/filter/CORSFilter.java
Labels: bug

#13 fix: dockerfile download dependencies from maven failure
  Dockerfile
Labels: bug

#14 implement list and create for store, tag, product, category
  src/main/java/com/cdcn/apartmentonlinemarket/products/controller/CategoryController.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/controller/ProductController.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/controller/TagController.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/dto/CategoryDTO.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/dto/ProductDTO.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/dto/TagDTO.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/mapper/CategoryMapper.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/mapper/ProductMapper.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/mapper/TagMapper.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/repository/CategoryRepository.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/repository/TagRepository.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/CategoryService.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/ProductService.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/ProductServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/TagService.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/impl/CategoryServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/impl/ProductServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/impl/TagServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/controller/StoreController.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/controller/StorePaymentGatewayController.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/domain/dto/StoreDTO.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/domain/dto/StorePaymentGatewayDTO.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/domain/mapper/StoreMapper.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/domain/mapper/StorePaymentGatewayMapper.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/repository/StorePaymentGatewayRepository.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/service/StorePaymentGatewayService.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/service/StoreService.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/service/StoreServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/service/impl/StorePaymentGatewayServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/stores/service/impl/StoreServiceImpl.java
Labels: enhancement

#15 fix: call isPresent() check null Optional instead of isEmpty()
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/impl/CategoryServiceImpl.java
Labels: bug

#16 fix: symbol method error in mapper class
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/mapper/CategoryMapper.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/mapper/ProductMapper.java
Labels: bug

#19 feat: api refresh token
  src/main/java/com/cdcn/apartmentonlinemarket/auth/controller/AuthController.java
  src/main/java/com/cdcn/apartmentonlinemarket/auth/dto/request/RefreshTokenRequest.java
  src/main/java/com/cdcn/apartmentonlinemarket/auth/service/AuthService.java
  src/main/java/com/cdcn/apartmentonlinemarket/auth/service/AuthServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/exception/InvalidRefreshTokenException.java
  src/main/java/com/cdcn/apartmentonlinemarket/exception/handler/GlobalHandleException.java
Labels: enhancement

#20 feat: filter products following criteria key-value && sort && pagination
  src/main/java/com/cdcn/apartmentonlinemarket/common/enums/FieldType.java
  src/main/java/com/cdcn/apartmentonlinemarket/common/enums/FilterOperator.java
  src/main/java/com/cdcn/apartmentonlinemarket/helpers/pagination/PageRequestBuilder.java
  src/main/java/com/cdcn/apartmentonlinemarket/helpers/response/PageResponse.java
  src/main/java/com/cdcn/apartmentonlinemarket/helpers/specs/FilterBuilder.java
  src/main/java/com/cdcn/apartmentonlinemarket/helpers/specs/FilterCriteria.java
  src/main/java/com/cdcn/apartmentonlinemarket/helpers/specs/FilterSpecifications.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/controller/ProductController.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/dto/request/SearchProductRequest.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/dto/request/SortRequest.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/ProductService.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/impl/ProductServiceImpl.java
Labels: enhancement

#26 feat: upload image for the product
  docker-compose-minio.yml
  nginx.conf
  src/main/java/com/cdcn/apartmentonlinemarket/ApartmentOnlineMarketApplication.java
  src/main/java/com/cdcn/apartmentonlinemarket/common/enums/CategoryStatus.java
  src/main/java/com/cdcn/apartmentonlinemarket/exception/CategoryNotFoundException.java
  src/main/java/com/cdcn/apartmentonlinemarket/exception/handler/GlobalHandleException.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/controller/ImageController.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/controller/ProductController.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/dto/ProductDTO.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/entity/Category.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/entity/Product.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/mapper/ProductMapper.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/repository/CategoryRepository.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/FilesStorageService.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/ProductService.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/impl/CategoryServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/impl/FilesStorageServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/impl/ProductServiceImpl.java
  src/main/resources/application-dev.yml
  uploads/306753461_534672878428103_5319688628401476222_n.jpg
  uploads/Screenshot from 2022-09-22 15-23-18.png
  uploads/Screenshot from 2022-10-17 16-20-16.png
  uploads/Screenshot from 2022-10-17 16-23-24.png
  uploads/Screenshot from 2022-11-22 15-34-04.png
  uploads/Screenshot from 2022-11-22 15-57-42.png
  uploads/Screenshot from 2022-11-22 22-05-30.png
  uploads/Screenshot from 2022-11-25 13-09-43.png
  uploads/Screenshot from 2022-12-09 18-18-56.png
  uploads/Screenshot from 2022-12-12 19-48-55.png
  uploads/Screenshot from 2022-12-12 19-54-33.png
  uploads/Screenshot from 2022-12-13 15-09-47.png
Labels: enhancement

#33 feat: create order
  src/main/java/com/cdcn/apartmentonlinemarket/common/enums/FilterOperator.java
  src/main/java/com/cdcn/apartmentonlinemarket/helpers/specs/FilterCriteria.java
  src/main/java/com/cdcn/apartmentonlinemarket/helpers/specs/FilterOperatorDeserializer.java
  src/main/java/com/cdcn/apartmentonlinemarket/helpers/specs/FilterSpecifications.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/controller/OrderController.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/domain/dto/CreateOrderResponse.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/domain/dto/OrderDto.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/domain/dto/OrderItemDto.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/domain/dto/request/CreateOrderRequest.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/domain/dto/request/OrderLineItem.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/domain/entity/Orders.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/domain/mapper/OrderItemMapper.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/domain/mapper/OrderMapper.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/model/OrderResponse.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/repository/OrderRepository.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/services/OrderItemService.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/services/OrderItemServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/services/OrderService.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/services/OrderServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/controller/ProductController.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/dto/request/SearchProductRequest.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/entity/Category.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/entity/Product.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/domain/entity/Recomment.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/InventoryService.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/impl/InventoryServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/products/services/impl/ProductServiceImpl.java
  src/main/java/com/cdcn/apartmentonlinemarket/users/domain/entity/Users.java
  src/main/java/com/cdcn/apartmentonlinemarket/users/repository/UserRepository.java
  uploads/Screenshot from 2022-09-30 21-07-12.png
  uploads/Screenshot from 2022-10-06 11-51-40.png
Labels: enhancement

#34 doc: update title readme.md
  README.md
Labels: documentation

#35 fix: data type attribute expiredAt entity order
  src/main/java/com/cdcn/apartmentonlinemarket/orders/domain/dto/CreateOrderResponse.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/domain/entity/Orders.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/model/OrderResponse.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/repository/OrderRepository.java
  src/main/java/com/cdcn/apartmentonlinemarket/orders/services/OrderServiceImpl.java
Labels: bug

#42 fix: filter product by category in specification
  src/main/java/com/cdcn/apartmentonlinemarket/common/enums/FieldType.java
  src/main/java/com/cdcn/apartmentonlinemarket/common/enums/FilterOperator.java
  src/main/java/com/cdcn/apartmentonlinemarket/helpers/specs/FilterSpecifications.java
Labels: bug

#44 Bugfix/upload image product
  src/main/java/com/cdcn/apartmentonlinemarket/products/controller/ProductController.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  uploads/Ao-hoodie-2-White-1-ZiZoou-Store.webp
Labels: bug
